
import React from 'react';
import { Warehouse, Category, Item, ItemStatus } from './types';

export const initialWarehouses: Warehouse[] = [
  { id: 'wh-1', name: 'Main North Hub', prefix: 'WHA' },
  { id: 'wh-2', name: 'South Logistics', prefix: 'WHB' },
  { id: 'wh-3', name: 'Central Distribution', prefix: 'WHC' },
  { id: 'wh-4', name: 'East Coast DC', prefix: 'WHE' },
];

export const initialCategories: Category[] = [
  // Main Categories
  { id: 'cat-construction', name: 'Construction', code: 'CON' },
  { id: 'cat-hotel', name: 'Hotel', code: 'HTL' },
  { id: 'cat-utility', name: 'Utility', code: 'UTL' },
  
  // Construction Sub-categories
  { id: 'cat-res', name: 'Residential', code: 'RES', parentId: 'cat-construction' },
  { id: 'cat-com', name: 'Commercial', code: 'COM', parentId: 'cat-construction' },
  { id: 'cat-ele', name: 'Electrical', code: 'ELE', parentId: 'cat-construction' },
  
  // Hotel Sub-categories
  { id: 'cat-btq', name: 'Boutique', code: 'BTQ', parentId: 'cat-hotel' },
  { id: 'cat-rst', name: 'Resorts', code: 'RST', parentId: 'cat-hotel' },
  { id: 'cat-ghs', name: 'Guest House', code: 'GHS', parentId: 'cat-hotel' },
  { id: 'cat-spa', name: 'Spa & Wellness', code: 'SPA', parentId: 'cat-hotel' },
  
  // Utility Sub-categories
  { id: 'cat-sad', name: 'Supply & Distribution', code: 'SAD', parentId: 'cat-utility' },
  { id: 'cat-wmr', name: 'Waste Management & Recycling', code: 'WMR', parentId: 'cat-utility' },
  { id: 'cat-tel', name: 'Telecommunications', code: 'TEL', parentId: 'cat-utility' },
];

export const initialItems: Item[] = [
  {
    id: 'it-1',
    name: 'Reinforcement Steel 12mm',
    warehouseId: 'wh-1',
    categoryId: 'cat-com',
    status: ItemStatus.RAW,
    barcode: 'WHA-COM-it-1',
    quantity: 450,
    baseCost: 120,
    freight: 15,
    duties: 10,
    taxes: 5,
    trueUnitCost: 150,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-2',
    name: 'Vintage Hotel Sheets (Set)',
    warehouseId: 'wh-2',
    categoryId: 'cat-ghs',
    status: ItemStatus.OLD_USED,
    barcode: 'WHB-GHS-it-2',
    quantity: 85,
    baseCost: 40,
    freight: 2,
    duties: 0,
    taxes: 8,
    trueUnitCost: 50,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-3',
    name: 'High-Speed Fiber Optic Coil',
    warehouseId: 'wh-3',
    categoryId: 'cat-tel',
    status: ItemStatus.FINISHED,
    barcode: 'WHC-TEL-it-3',
    quantity: 20,
    baseCost: 200,
    freight: 40,
    duties: 20,
    taxes: 30,
    trueUnitCost: 290,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-4',
    name: 'Plywood Sheets 18mm',
    warehouseId: 'wh-1',
    categoryId: 'cat-res',
    status: ItemStatus.RAW,
    barcode: 'WHA-RES-it-4',
    quantity: 120,
    baseCost: 850,
    freight: 50,
    duties: 0,
    taxes: 100,
    trueUnitCost: 1000,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-5',
    name: 'Portland Cement Grade 40',
    warehouseId: 'wh-4',
    categoryId: 'cat-res',
    status: ItemStatus.RAW,
    barcode: 'WHE-RES-it-5',
    quantity: 500,
    baseCost: 220,
    freight: 30,
    duties: 0,
    taxes: 25,
    trueUnitCost: 275,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-6',
    name: 'Industrial Hammer Drill',
    warehouseId: 'wh-1',
    categoryId: 'cat-com',
    status: ItemStatus.GOOD_AS_NEW,
    barcode: 'WHA-COM-it-6',
    quantity: 12,
    baseCost: 4500,
    freight: 200,
    duties: 150,
    taxes: 500,
    trueUnitCost: 5350,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-7',
    name: 'Reflective Safety Vest XL',
    warehouseId: 'wh-3',
    categoryId: 'cat-com',
    status: ItemStatus.FINISHED,
    barcode: 'WHC-COM-it-7',
    quantity: 300,
    baseCost: 150,
    freight: 10,
    duties: 5,
    taxes: 15,
    trueUnitCost: 180,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-8',
    name: 'THHN Copper Wire 2.5mm²',
    warehouseId: 'wh-2',
    categoryId: 'cat-ele',
    status: ItemStatus.RAW,
    barcode: 'WHB-ELE-it-8',
    quantity: 50,
    baseCost: 3200,
    freight: 100,
    duties: 200,
    taxes: 400,
    trueUnitCost: 3900,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-9',
    name: 'Smart LED Panel 60x60',
    warehouseId: 'wh-1',
    categoryId: 'cat-btq',
    status: ItemStatus.FINISHED,
    barcode: 'WHA-BTQ-it-9',
    quantity: 80,
    baseCost: 1200,
    freight: 80,
    duties: 50,
    taxes: 150,
    trueUnitCost: 1480,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-10',
    name: 'Aromatic Spa Massage Oil',
    warehouseId: 'wh-2',
    categoryId: 'cat-spa',
    status: ItemStatus.FINISHED,
    barcode: 'WHB-SPA-it-10',
    quantity: 150,
    baseCost: 450,
    freight: 20,
    duties: 10,
    taxes: 40,
    trueUnitCost: 520,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-11',
    name: 'Wicker Resort Sun Lounger',
    warehouseId: 'wh-4',
    categoryId: 'cat-rst',
    status: ItemStatus.FINISHED,
    barcode: 'WHE-RST-it-11',
    quantity: 40,
    baseCost: 5500,
    freight: 800,
    duties: 400,
    taxes: 600,
    trueUnitCost: 7300,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-12',
    name: 'Compact Electric Kettle 1.2L',
    warehouseId: 'wh-3',
    categoryId: 'cat-ghs',
    status: ItemStatus.FINISHED,
    barcode: 'WHC-GHS-it-12',
    quantity: 200,
    baseCost: 650,
    freight: 40,
    duties: 30,
    taxes: 80,
    trueUnitCost: 800,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-13',
    name: 'Luxury Egyptian Cotton Robe',
    warehouseId: 'wh-2',
    categoryId: 'cat-btq',
    status: ItemStatus.GOOD_AS_NEW,
    barcode: 'WHB-BTQ-it-13',
    quantity: 65,
    baseCost: 1800,
    freight: 50,
    duties: 100,
    taxes: 200,
    trueUnitCost: 2150,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-14',
    name: 'High-Density PVC Pipe 4"',
    warehouseId: 'wh-4',
    categoryId: 'cat-sad',
    status: ItemStatus.RAW,
    barcode: 'WHE-SAD-it-14',
    quantity: 240,
    baseCost: 450,
    freight: 60,
    duties: 0,
    taxes: 40,
    trueUnitCost: 550,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-15',
    name: 'Galvanized Waste Bin 120L',
    warehouseId: 'wh-3',
    categoryId: 'cat-wmr',
    status: ItemStatus.FINISHED,
    barcode: 'WHC-WMR-it-15',
    quantity: 35,
    baseCost: 2800,
    freight: 300,
    duties: 0,
    taxes: 350,
    trueUnitCost: 3450,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-16',
    name: 'L3 Managed Network Switch',
    warehouseId: 'wh-1',
    categoryId: 'cat-tel',
    status: ItemStatus.FINISHED,
    barcode: 'WHA-TEL-it-16',
    quantity: 15,
    baseCost: 18500,
    freight: 500,
    duties: 1200,
    taxes: 2500,
    trueUnitCost: 22700,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-17',
    name: 'Electrical Transformer Oil',
    warehouseId: 'wh-2',
    categoryId: 'cat-sad',
    status: ItemStatus.RAW,
    barcode: 'WHB-SAD-it-17',
    quantity: 20,
    baseCost: 12500,
    freight: 1200,
    duties: 800,
    taxes: 1500,
    trueUnitCost: 16000,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-18',
    name: 'Monocrystalline Solar Panel',
    warehouseId: 'wh-4',
    categoryId: 'cat-sad',
    status: ItemStatus.FINISHED,
    barcode: 'WHE-SAD-it-18',
    quantity: 100,
    baseCost: 4200,
    freight: 400,
    duties: 200,
    taxes: 500,
    trueUnitCost: 5300,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-19',
    name: 'Porcelain Floor Tiles (60x60)',
    warehouseId: 'wh-1',
    categoryId: 'cat-com',
    status: ItemStatus.RAW,
    barcode: 'WHA-COM-it-19',
    quantity: 400,
    baseCost: 85,
    freight: 15,
    duties: 5,
    taxes: 15,
    trueUnitCost: 120,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-20',
    name: 'Split-Type Aircon 1.5HP',
    warehouseId: 'wh-3',
    categoryId: 'cat-ghs',
    status: ItemStatus.FINISHED,
    barcode: 'WHC-GHS-it-20',
    quantity: 25,
    baseCost: 22000,
    freight: 1500,
    duties: 1000,
    taxes: 3000,
    trueUnitCost: 27500,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'it-21',
    name: 'Galvanized Hex Bolts M12',
    warehouseId: 'wh-4',
    categoryId: 'cat-res',
    status: ItemStatus.RAW,
    barcode: 'WHE-RES-it-21',
    quantity: 2000,
    baseCost: 8,
    freight: 1,
    duties: 0.5,
    taxes: 1.5,
    trueUnitCost: 11,
    lastUpdated: new Date().toISOString(),
  },
];
